# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75ff53a1b812b6e78794cc46c371e7f6c63928bdac2e1a211b17c07e1f078bb188119a7616192e4a950610cb0c6ae2977e7b9e489a559073b06276f69c05675e

test:
  secret_key_base: dfa6b8095caaa1df0ee307b1bfb11e0e44b3fd7ca49b9a32ca733b551752269528873191a141d1d42b4a8e5505de00dbf1575e5f55714d0ab0c10c6de6272d1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
